version: '3.1'
services:
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=sma
      - POSTGRES_USER=sma
      - POSTGRES_DB=social_media_db
    networks:
      - sma

networks:
  sma:
    driver: bridge
